### ISSUE TITLE
Component broken - TypeError: timeout() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by alpat59** [cytech/Home-Assistant-wundergroundpws#94]
After the updraft to 2022.3 The component doesn’t work and I’m getting the following message:
TypeError: timeout() got an unexpected keyword argument 'loop'

It seems an error occurred also to other custom components (https://github.com/home-assistant/core/issues/67505)

thank you for your support

**Comment by alpat59** [comment]
I read just now the closed issues about updating to 0.8.1… sorry for duplicating .. I’ll do it and come back with feedback.

**Comment by dxdx65** [comment]
Hello ,
@alpat59 : did you succed in getting the component work updating to 0.8.1? 

I tried with no success..: HA 2022.3.4 OA 7.4  SUP 2022.3.4
Since I updated to 2022.3.x  I always get an error at line 562 of sensors.py:


Logger: custom_components.wundergroundpws.sensor
Source: custom_components/wundergroundpws/sensor.py:562
Integration: wundergroundpws (documentation, issues)
First occurred: 13:43:24 (27 occurrences)
Last logged: 14:53:57

    Error fetching WUnderground data: ContentTypeError(RequestInfo(url=URL('https://api.weather.com/v2/pws/observations/current?stationId=MYSTATION&format=json&units=m&apiKey=0000000000000000000000000&numericPrecision=decimal'), method='GET', headers=<CIMultiDictProxy('Host': 'api.weather.com', 'User-Agent': 'HomeAssistant/2022.2.2 aiohttp/3.8.1 Python/3.9', 'Accept-Encoding': 'gzip', 'Accept': '*/*')>, real_url=URL('https://api.weather.com/v2/pws/observations/current?stationId=MYSTATION&format=json&units=m&apiKey=0000000000000000000000000&numericPrecision=decimal')), (), message='Attempt to decode JSON with unexpected mimetype: text/html', headers=<CIMultiDictProxy('Content-Type': 'text/html', 'Content-Length': '133', 'Expires': 'Mon, 14 Mar 2022 13:41:57 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Mon, 14 Mar 2022 13:41:57 GMT', 'Connection': 'keep-alive', 'Content-Security-Policy': "default-src 'none'", 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=86400')>)
......
